SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WeddingSites' AND COLUMN_NAME='ceremony_start_time')
    ALTER TABLE dbo.WeddingSites ADD ceremony_start_time VARCHAR(10) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WeddingSites' AND COLUMN_NAME='ceremony_end_time')
    ALTER TABLE dbo.WeddingSites ADD ceremony_end_time VARCHAR(10) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WeddingSites' AND COLUMN_NAME='reception_start_time')
    ALTER TABLE dbo.WeddingSites ADD reception_start_time VARCHAR(10) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WeddingSites' AND COLUMN_NAME='reception_end_time')
    ALTER TABLE dbo.WeddingSites ADD reception_end_time VARCHAR(10) NULL;

COMMIT TRANSACTION;
